services:
    App\Auth\Infrastructure\OAuth2\TestClientManagerSetup:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setupTestClient, priority: 1000 }
        arguments:
            - '@league.oauth2_server.manager.in_memory.client'
            - '%env(OAUTH_DEFAULT_CLIENT_ID)%'
            - '%env(OAUTH_DEFAULT_CLIENT_SECRET)%'