api_platform:
    defaults:
        stateless: true

    mapping:
        paths:
            - '%kernel.project_dir%/src/User/Infrastructure/ApiPlatform/Resource'

    exception_to_status:
        App\User\Domain\Exception\UserAlreadyExistsException: 409
