framework:
    rate_limiter:
        login_ip:
            policy: sliding_window
            limit: 20
            interval: 15 minutes
            lock_factory: lock.factory
        login_identifier:
            policy: sliding_window
            limit: 5
            interval: 15 minutes
            lock_factory: lock.factory
        api_default:
            policy: sliding_window
            limit: 60
            interval: 1 minute
            lock_factory: lock.factory

when@test:
    framework:
        rate_limiter:
            login_ip:
                policy: sliding_window
                limit: 3
                interval: 10 seconds
                lock_factory: lock.factory
                storage_service: limiter.storage.in_memory
            login_identifier:
                policy: sliding_window
                limit: 5
                interval: 10 seconds
                lock_factory: lock.factory
                storage_service: limiter.storage.in_memory
            api_default:
                policy: sliding_window
                limit: 5
                interval: 10 seconds
                lock_factory: lock.factory
                storage_service: limiter.storage.in_memory
